CREATE DATABASE TULIA;

CREATE TABLE Clients (
ClientID VARCHAR(255) PRIMARY KEY,
C_Name VARCHAR(255),
Gender VARCHAR(10)
);

DROP database tulia;

CREATE TABLE Rooms (
RoomID VARCHAR(255) PRIMARY KEY,
RoomNo INT AUTO_INCREMENT UNIQUE,
Size VARCHAR(255),
Cost float(10,2)
/*Room_Status INT DEFAULT 0*/
);

CREATE TABLE Bookings (
BookingID VARCHAR(255) PRIMARY KEY,
CheckIN TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
CheckOUT DATETIME
)